-- Création de la table des appels
CREATE TABLE appels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    date TEXT NOT NULL,
    time TEXT NOT NULL,
    duration TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('qualifié', 'non qualifié', 'sans réponse', 'répondu')),
    result TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insertion de données d'exemple
INSERT INTO appels (name, date, time, duration, status, result) VALUES
('Jean Dupont', '2023-06-12', '14:30', '3:45', 'qualifié', 'Intéressé - À rappeler'),
('Marie Martin', '2023-06-12', '15:15', '2:23', 'non qualifié', 'Pas intéressé'),
('Pierre Lefebvre', '2023-06-11', '10:00', '1:48', 'sans réponse', 'Messagerie'),
('Sophie Bernard', '2023-06-11', '11:30', '4:12', 'qualifié', 'RDV pris'),
('Thomas Petit', '2023-06-10', '09:45', '2:55', 'répondu', 'À rappeler plus tard'),
('Julie Moreau', '2023-06-10', '16:20', '3:10', 'qualifié', 'Demande de documentation'),
('Nicolas Roux', '2023-06-09', '13:15', '0:45', 'sans réponse', 'Occupé'),
('Camille Dubois', '2023-06-09', '14:45', '5:20', 'qualifié', 'RDV pris');

-- Création d'une politique RLS (Row Level Security) pour protéger les données
ALTER TABLE appels ENABLE ROW LEVEL SECURITY;

-- Création d'une politique permettant la lecture pour les utilisateurs authentifiés
CREATE POLICY "Les utilisateurs authentifiés peuvent lire les appels" 
ON appels FOR SELECT 
USING (auth.role() = 'authenticated');

-- Création d'une politique permettant l'insertion pour les utilisateurs authentifiés
CREATE POLICY "Les utilisateurs authentifiés peuvent ajouter des appels" 
ON appels FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

-- Création d'une politique permettant la mise à jour pour les utilisateurs authentifiés
CREATE POLICY "Les utilisateurs authentifiés peuvent modifier des appels" 
ON appels FOR UPDATE 
USING (auth.role() = 'authenticated'); 